services:
  oscata:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: oscata
    ports:
      - "47860:47860"
    environment:
      OSCATA_WEBGUI_PORT: "47860"
      OSCATA_WEBGUI_EXPOSED_PORT: "47860"  # cambia al puerto externo si usas un proxy inverso
    volumes:
      - oscata-config:/config
      - oscata-downloads:/downloads
    restart: unless-stopped

volumes:
  oscata-config:
  oscata-downloads:
