services:
  ftp-dev:
    image: delfer/alpine-ftp-server
    container_name: oscata-ftp-dev
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      USERS: "oscata|oscata123|/ftp/media|10000"
      ADDRESS: localhost
      MIN_PORT: 21000
      MAX_PORT: 21010
    volumes:
      - ./media:/ftp/media
    restart: unless-stopped
